on:
  push:
    branches:
      - GA
env:
  PAT: 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

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: 1.19.2

      - name: Setup Java and Maven
        uses: devonfw-actions/java-maven-setup@v1

      - name: Configure access to download dependencies in Go
        shell: bash
        run: git config --global url."https://$PAT:@github.com/TakeoffTech/".insteadOf "https://github.com/TakeoffTech/"

      - name: Build
        shell: bash
        run: make build


